version: '3.8'

services:
  backend:
    build: ./chat_app_backend/chat_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./chat_app_backend/chat_app:/usr/src/chat_app_backend/chat_app
    ports:
      - 8000:8000