version: '3.8'

services:

  backend:
    build: ./chat_app_backend/chat_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./chat_app_backend/chat_app:/usr/src/chat_app_backend/chat_app
    ports:
      - 8000:8000

  frontend:
    build: ./chat_app_frontend
    command: npm start
    volumes:
      - /app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true